# Generated by Django 5.2.1 on 2025-05-09 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("movie", "Фильм"),
                            ("series", "Сериал"),
                            ("book", "Книга"),
                        ],
                        max_length=10,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "genre",
                    models.CharField(blank=True, max_length=100, verbose_name="Жанр"),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        verbose_name="Рейтинг",
                    ),
                ),
                (
                    "release_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата релиза"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст рецензии")),
                (
                    "rating",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Оценка"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата публикации"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="catalog.work",
                        verbose_name="Произведение",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ListEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("want", "Хочу посмотреть/прочитать"),
                            ("watched", "Просмотрено/Прочитано"),
                        ],
                        default="want",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="list_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="list_entries",
                        to="catalog.work",
                        verbose_name="Произведение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись списка",
                "verbose_name_plural": "Записи списка",
                "unique_together": {("work", "user")},
            },
        ),
    ]
