# Generated by Django 5.2.1 on 2025-05-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="listentry",
            name="favorite",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listentry",
            name="finish_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listentry",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="listentry",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="listentry",
            name="progress",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="listentry",
            name="rewatches",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="listentry",
            name="score",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listentry",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="listentry",
            name="added_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
