# Generated by Django 5.2.1 on 2025-05-13 18:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_listentry_favorite_listentry_finish_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listentry",
            old_name="rewatches",
            new_name="rewatch_count",
        ),
    ]
