# Generated by Django 5.2.1 on 2025-05-14 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_rename_rewatches_listentry_rewatch_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listentry",
            name="score",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Оценка от 0.0 до 10.0 с одним знаком после запятой",
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
