# Generated by Django 5.2.1 on 2025-05-14 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_alter_listentry_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listentry",
            name="score",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="listentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("want", "Хочу посмотреть/Хочу прочитать"),
                    ("reading", "Смотрю/Читаю"),
                    ("completed", "Просмотрено/Прочитано"),
                    ("rewatching", "Пересматриваю/Перечитываю"),
                    ("paused", "Приостановлено/На паузе"),
                    ("dropped", "Брошено/Брошено"),
                ],
                default="want",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
