# Generated by Django 5.2.1 on 2025-05-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_activity_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="detail",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="work",
            name="openlibrary_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="work",
            name="poster_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="work",
            name="tmdb_id",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
