# Generated by Django 5.2.1 on 2025-05-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0010_work_external_id_work_genres_text_work_overview_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="external_url",
            field=models.URLField(blank=True, help_text="URL на TMDB"),
        ),
    ]
