# Generated by Django 5.2.1 on 2025-05-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0011_work_external_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="work",
            name="external_url",
        ),
        migrations.AlterField(
            model_name="work",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="TMDB external id вида 'movie:123' / 'tv:456'",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
